name: smartpot-mail

services:
  mail-smartpot:
    build: .
    image: ghcr.io/smartpottech/smartpot-mail:latest
    container_name: smartpot-mail
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    env_file:
      - .env
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"
    tmpfs:
      - /tmp
