name: Dockerization of the mail service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_NAME: ${{ secrets.DOCKER_APP_NAME }}
  USERNAME: ${{ secrets.DOCKER_USERNAME }}
  PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_TAG: ${{ secrets.DOCKER_APP_TAG }}

jobs:
  dockerization:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Revisi贸n de c贸digo
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 2: Configuraci贸n de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Paso 3: Construcci贸n de la imagen Docker
      - name: Build the Docker image
        run: docker build --platform linux/amd64 -t ${{ env.USERNAME }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }} .

      # Paso 4: Loguearse en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      # Paso 5: Push de la imagen Docker a Docker Hub
      - name: Push Docker image
        run: docker push ${{ env.USERNAME }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}